### PR TITLE
Use version 2 of the Export API in samples

### PR DESCRIPTION
**Pull request by facewindu**
Use version 2 of the export API in samples.
To be merged after Gradle Enterprise 2021.2 has been released.

### CODE REVIEW

**Review by ldaley — CHANGES_REQUESTED** [review]
We'll need to explain somewhere what the minimum version of Gradle Enterprise is for these to work.

**Review by ldaley — CHANGES_REQUESTED** [review]
Did you test that the samples work with v2? Specifically, I'm wondering about the renamed fields.

**Comment by facewindu** [comment]
> Did you test that the samples work with v2? Specifically, I'm wondering about the renamed fields.

Tested the javascript sample. The thing it does is not impacted.
I slightly changed the java sample, as it was not working for non Gradle build tools (always checking the BuildAgent event, and requiring to find a single event there)
PTAL @ldaley

**Review by ldaley — APPROVED** [review]

**Comment by facewindu** [comment]
Waiting for the Gradle Enterprise 2021.2 release to merge this

**Pull request merged**
